---
title: "ModernDive Ch 5: Basic Regression"
output: html_notebook
---

```{r}
# Load libraries
library(tidyverse)
library(moderndive)
library(skimr)
library(gapminder)
```

### 5.1 One numerical explanatory variable
#### 5.1.1 Exploratory data analysis

```{r}
# Select columns from evals
evals_ch5 <-
  evals %>% 
  select(ID, score, bty_avg, age)

evals_ch5
  
```

```{r}
 # Here are three common steps in an EDA:

  #   Most crucially, looking at the raw data values.
  #   Computing summary statistics, such as means, medians, and interquartile ranges.
  #   Creating data visualizations.

```

```{r}
# Look at the raw data
glimpse(evals_ch5)
```

```{r}
# Random sample
evals_ch5 %>% 
  slice_sample(n = 5)
```

```{r}
# Create summaries
evals_ch5 %>% 
  summarise(
    mean_bty_average = mean(bty_avg),
    mean_score = mean(score),
    median_bty_average = median(bty_avg),
    median_score = median(score)
  )
```

```{r}
# skimr:skim
evals_ch5 %>% 
  select(score, bty_avg) %>% 
  skimr::skim()

```

```{r}
# Correlation coeff
evals_ch5 %>% 
get_correlation(score ~ bty_avg)
```

```{r}
# Alternative way to correlate
evals_ch5 %>% 
  summarise(correlation = cor(score, bty_avg))
```

```{r}
# Exploratory visualization
evals_ch5 %>%
  ggplot(aes(bty_avg, score)) +
  geom_point() +
  labs(x = "Beauty Score",
       y = "Teaching Score",
       title = "Relationship of teaching and beauty scores")
```

```{r}
# Remove overplotting
evals_ch5 %>%
  ggplot(aes(bty_avg, score)) +
  geom_jitter() +
  labs(x = "Beauty Score",
       y = "Teaching Score",
       title = "Relationship of teaching and beauty scores")
```

```{r}
# Add best fitting line
evals_ch5 %>%
  ggplot(aes(bty_avg, score)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Beauty Score",
       y = "Teaching Score",
       title = "Relationship of teaching and beauty scores")

```

```{r}
# (LC5.1) Conduct a new exploratory data analysis with the same outcome 
# variable y being score but with age as the new explanatory variable x. 

# Remember, this involves three things:

  #  Looking at the raw data values.
  #  Computing summary statistics.
  #  Creating data visualizations.

# What can you say about the relationship between age and teaching scores based 
# on this exploration?

# Answer: There appears to be a very small negative correlation between score and
# the age of the teacher (score reduces with age)

glimpse(evals_ch5)
```

```{r}
# Summary stats
evals_ch5 %>% 
  select(score, age) %>% 
  skimr::skim()
```

```{r}
# Correlation
evals_ch5 %>% 
  get_correlation(score ~ age)
```


```{r}
# Plotting
evals_ch5 %>% 
  ggplot(aes(age, score)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

#### 5.1.2 Simple linear regression
```{r}
# Fit regrssion model
score_model <- lm(score ~ bty_avg, data = evals_ch5)

# Get regression table
get_regression_table(score_model)
```

```{r}
# (LC5.2) 
# Fit a new simple linear regression using lm(score ~ age, data = evals_ch5) 
# where age is the new explanatory variable x. Get information about the “best-fitting” 
# line from the regression table by applying the get_regression_table() function. 
# How do the regression results match up with the results from your earlier exploratory data analysis?

evals_ch5 %>% 
  lm(score ~ age, data = .) %>% 
  get_regression_table()

# Answer: The slope is very slightly negative (-0.006). This fist with the correaltion 
  # that is slightly negative (-0.1). The slope intercept seems equal to the trend line.
```

#### 5.1.3 Observed/fitted values and residuals

```{r}
# Get regression points
regression_points <- get_regression_points(score_model)
regression_points
```

```{r}
# (LC5.3) Generate a data frame of the residuals of the model where 
# you used age as the explanatory x variable.

evals_ch5 %>% 
  lm(score ~ age, data = .) %>% 
  get_regression_points()
```

#### 5.2 One categorical explanatory variable

```{r}
# filter and select from gapminder
gapminder_2007 <-
  gapminder %>% 
  filter(year == 2007) %>% 
  select(country, lifeExp, continent, gdpPercap)

glimpse(gapminder_2007)
```

```{r}
# random sample

gapminder_2007 %>% 
  slice_sample(n = 5)
```

```{r}
# skim

gapminder_2007 %>% 
  select(lifeExp, continent) %>% 
  skimr::skim()
```

```{r}
# Visualize
gapminder_2007 %>% 
  ggplot(aes(lifeExp)) +
  geom_histogram(binwidth = 5, color = "white") + 
  labs(x = "Life Expectancy", y = "Number of countries",
       title = "Histogram of distributions of worldwide life expectancies")
```

```{r}
# Visualize with facets
gapminder_2007 %>% 
  ggplot(aes(lifeExp)) +
  geom_histogram(binwidth = 5, color = "white") + 
  labs(
    x = "Life Expectancy", y = "Number of countries",
    title = "Histogram of distributions of worldwide life expectancies"
  ) +
  facet_wrap(~ continent, nrow = 2)
```

```{r}
# Boxplot

gapminder_2007 %>% 
  ggplot(aes(continent, lifeExp)) +
  geom_boxplot() +
  labs(
    x = "Continent", 
    y = "Life expectancy", 
    title = "Life expectancy by continent"
  )
```

```{r}
# Compute median and mean
lifeExp_by_continent <-
  gapminder_2007 %>% 
  group_by(continent) %>% 
  summarise(median = median(lifeExp),
            mean = mean(lifeExp))
lifeExp_by_continent
```

```{r}
# Mean lifeExp by continent and relative diff from mean for Africa
lifeExp_by_continent %>% 
  mutate(`Difference versus Africa` = mean - mean[1])
```

```{r}
# (LC5.4) Conduct a new exploratory data analysis with the same explanatory # variable x being continent but with gdpPercap as the new outcome variable # y. What can you say about the differences in GDP per capita 
# between continents based on this exploration?

gapminder_2007 %>% 
  ggplot(aes(continent, gdpPercap)) +
  geom_boxplot() +
  geom_point()

# Answer: Europe and Oceania have clearly the highest gdpPercap,
  # Asia has a low median, but with some countries with high gdpPercap,
  # Americas is low, but two countries (Canada and USA?) have high values,
  # African countries score very low

```


#### 5.2.2 Linear regression

```{r}
# with categorical explanatory variable

lifeExp_model <-
  gapminder_2007 %>% 
  lm(lifeExp ~ continent, data = .)

lifeExp_model %>% get_regression_table()
```

```{r}
# (LC5.5) Fit a new linear regression using lm(gdpPercap ~ continent, 
# data = gapminder2007) where gdpPercap is the new outcome variable y. 
# Get information about the “best-fitting” line from the regression 
# table by applying the get_regression_table() function. How do the 
# regression results match up with the results from your previous 
# exploratory data analysis?

gapminder_2007 %>% 
  lm(gdpPercap ~ continent, data = .) %>% 
  get_regression_table()

# Answer: They mach as expected. Africa is the baseline; however,
  # The mean values are quite different from the median in some cases.
```

#### 5.2.3 Observed/fitted values and residuals
```{r}
regression_points <- get_regression_points(lifeExp_model, ID = "country")
regression_points
```

```{r}
# (LC5.6) Using either the sorting functionality of RStudio’s spreadsheet viewer or using the data wrangling tools you learned in Chapter 3, identify the five countries with the five smallest (most negative) residuals? What do these negative residuals say about their life expectancy relative to their continents’ life expectancy?

regression_points %>% 
  slice_min(residual, n = 5)

# A: These countries all have negative residuals meaning a lower lifeExp
  # than the average lifeExp of the corresponding continent
```

```{r}
# (LC5.7) Repeat this process, but identify the five countries with the five largest (most positive) residuals. What do these positive residuals say about their life expectancy relative to their continents’ life expectancy?

regression_points %>% 
  slice_max(residual, n = 5)

# A: These countries all have positive residuals meaning a higher lifeExp
  # than the average lifeExp of the corresponding continent
```

### 5.3 Related topics
#### 5.3.1 Correlation is not necessarily causation

```{r}
# Compute the sum of squared residuals
score_model %>% 
  get_regression_points() %>% 
  mutate(squared_residual = residual^2 ) %>% 
  summarise(sum_of_squared_residuals = sum(squared_residual))
```

```{r}
# (LC5.8) Note in Figure 5.13 there are 3 points marked with dots and:

  #  The “best” fitting solid regression line in blue
  #  An arbitrarily chosen dotted red line
  #  Another arbitrarily chosen dashed green line

# Compute the sum of squared residuals by hand for each line and show that of these three lines, the regression line in blue has the smallest value.

red_dotted <- (c((2 - 2.5), (1 - 2.5), (3 - 2.5))^2) %>% sum()
green_dashed <- (c((2 - 2), (1 - 1), (3 - 1))^2) %>% sum()
best_fit <- (c((2 - 1.5), (1 - 2), (3 - 2.5))^2) %>% sum()

best_fit < red_dotted & green_dashed
```